---

- name: install linux headers
  apt:
    name: 'linux-headers-{{ ansible_kernel }}'
    update_cache: yes
    state: present

- name: copy sdc debian package
  file:
    src: '{{ scaleio_sdc_source_file_path }}'
    dest: '/tmp/{{ scaleio_sdc_source_file_path | basename }}'
    owner: root
    group: root

- name: install deb package
  apt:
    environment: "MDM_IP={{ scaleio_sdc_mdm_servers | join(',') }}"
    deb: '/tmp/{{ scaleio_sdc_source_file_path | basename }}'
